this.usernameが取れません
cloto-jp/cloto pull request #69
Opened 2021-04-07 00:07 UTC by tkknot

ProfileDialog.vueではthis.usernameが取れてたんですが、
当ファイルだと取れませんでした。

現在はshowFollowsメソッドにcreatedメソッドと同じ文が入っており、
仮にthis.usenameにログインしているユーザーの名前が入れば正しくデータが取れるといった感じです。

一瞥お願いいたします。

2021-04-07 00:13 UTC, tkknot reviewed
プルリの出し方等、変だったらお申し付けください

2021-04-08 14:20 UTC, a2h1r0 requested changes
この状態でmergeしてしまうと，developブランチに動かないコードが取り込まれることになるため（マイページにメニューが追加されるが，実際は動かない），適切ではない．

2021-04-08 14:20 UTC, a2h1r0 commented on resources/js/views/mypage/Follow.vue
> +      let response = await axios.get('/api/users/' + this.username);
なんとなくやりたいことはわかりますが，一度口頭でご説明します．

2021-04-09 00:24 UTC, tkknot commented
#55 コミット通りなんとか動くものが完成しました。。。
ご確認お願いします。

2021-04-10 13:04 UTC, a2h1r0 approved these changes
修正箇所の対応はこちらで行いますので，次のタスクをお願いします．（明日相談しましょう．）

2021-04-10 13:04 UTC, a2h1r0 commented on resources/js/views/mypage/Follow.vue
> +      this.user = this.authUser;
ここの処理は必要ない気がする．

2021-04-10 13:04 UTC, a2h1r0 commented on resources/js/views/mypage/Follow.vue
> +    showFollows: async function () {
必ずJSDocで処理の説明を書いてください．

2021-04-10 13:06 UTC, merged